<?xml version="1.0" encoding="utf-8"?><Database Name="Pet Shop Database" Class="PetShopDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=CCL01-11;Initial Catalog=&quot;Pet Shop Database&quot;;Integrated Security=True;Connect Timeout=30;Encrypt=False;Trust Server Certificate=False" SettingsObjectName="PetShop.Properties.Settings" SettingsPropertyName="Pet_Shop_DatabaseConnectionString3" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="Account_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffRole_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Account_Password" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StaffRole_Account" Member="StaffRole" ThisKey="StaffRole_ID" OtherKey="StaffRole_ID" Type="StaffRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Item" Member="Items">
    <Type Name="Item">
      <Column Name="Item_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Item_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Availability" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Item_Log" Member="Logs" ThisKey="Item_ID" OtherKey="Item_ID" Type="Log" />
      <Association Name="Item_Purchase" Member="Purchases" ThisKey="Item_ID" OtherKey="Item_ID" Type="Purchase" />
    </Type>
  </Table>
  <Table Name="dbo.Logs" Member="Logs">
    <Type Name="Log">
      <Column Name="Logs_ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Logs_Date" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Logs_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Purchase_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Item_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Item_Log" Member="Item" ThisKey="Item_ID" OtherKey="Item_ID" Type="Item" IsForeignKey="true" />
      <Association Name="Origin_Log" Member="Origin" ThisKey="Origin_ID" OtherKey="Origin_ID" Type="Origin" IsForeignKey="true" />
      <Association Name="Owner_Log" Member="Owner" ThisKey="Owners_ID" OtherKey="Owners_ID" Type="Owner" IsForeignKey="true" />
      <Association Name="Pet_Log" Member="Pet" ThisKey="Pet_ID" OtherKey="Pet_ID" Type="Pet" IsForeignKey="true" />
      <Association Name="Purchase_Log" Member="Purchase" ThisKey="Purchase_ID" OtherKey="Purchase_ID" Type="Purchase" IsForeignKey="true" />
      <Association Name="Staff_Log" Member="Staff" ThisKey="Staff_ID" OtherKey="Staff_ID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Origin" Member="Origins">
    <Type Name="Origin">
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Origin_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ContactNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Origin_Log" Member="Logs" ThisKey="Origin_ID" OtherKey="Origin_ID" Type="Log" />
      <Association Name="Origin_Pet" Member="Pets" ThisKey="Origin_ID" OtherKey="Origin_ID" Type="Pet" />
    </Type>
  </Table>
  <Table Name="dbo.Owners" Member="Owners">
    <Type Name="Owner">
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Owners_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ContactNumber" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Owner_Log" Member="Logs" ThisKey="Owners_ID" OtherKey="Owners_ID" Type="Log" />
      <Association Name="Owner_Pet" Member="Pets" ThisKey="Owners_ID" OtherKey="Owners_ID" Type="Pet" />
      <Association Name="Owner_Purchase" Member="Purchases" ThisKey="Owners_ID" OtherKey="Owners_ID" Type="Purchase" />
    </Type>
  </Table>
  <Table Name="dbo.Pet" Member="Pets">
    <Type Name="Pet">
      <Column Name="Pet_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Pet_Log" Member="Logs" ThisKey="Pet_ID" OtherKey="Pet_ID" Type="Log" />
      <Association Name="Pet_Purchase" Member="Purchases" ThisKey="Pet_ID" OtherKey="Pet_ID" Type="Purchase" />
      <Association Name="Origin_Pet" Member="Origin" ThisKey="Origin_ID" OtherKey="Origin_ID" Type="Origin" IsForeignKey="true" />
      <Association Name="Owner_Pet" Member="Owner" ThisKey="Owners_ID" OtherKey="Owners_ID" Type="Owner" IsForeignKey="true" />
      <Association Name="Vaccine_Pet" Member="Vaccine" ThisKey="Vaccine_ID" OtherKey="Vaccine_ID" Type="Vaccine" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Purchase" Member="Purchases">
    <Type Name="Purchase">
      <Column Name="Purchase_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Pet_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Item_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Item_Quantity" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Purchase_Total" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Purchase_Date" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Customer_Number" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Purchase_Log" Member="Logs" ThisKey="Purchase_ID" OtherKey="Purchase_ID" Type="Log" />
      <Association Name="Item_Purchase" Member="Item" ThisKey="Item_ID" OtherKey="Item_ID" Type="Item" IsForeignKey="true" />
      <Association Name="Owner_Purchase" Member="Owner" ThisKey="Owners_ID" OtherKey="Owners_ID" Type="Owner" IsForeignKey="true" />
      <Association Name="Pet_Purchase" Member="Pet" ThisKey="Pet_ID" OtherKey="Pet_ID" Type="Pet" IsForeignKey="true" />
      <Association Name="Staff_Purchase" Member="Staff" ThisKey="Staff_ID" OtherKey="Staff_ID" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="Staff_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Staff_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffRole_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Photo" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Staff_Log" Member="Logs" ThisKey="Staff_ID" OtherKey="Staff_ID" Type="Log" />
      <Association Name="Staff_Purchase" Member="Purchases" ThisKey="Staff_ID" OtherKey="Staff_ID" Type="Purchase" />
      <Association Name="StaffRole_Staff" Member="StaffRole" ThisKey="StaffRole_ID" OtherKey="StaffRole_ID" Type="StaffRole" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.StaffRole" Member="StaffRoles">
    <Type Name="StaffRole">
      <Column Name="StaffRole_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffRole_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="StaffRole_Account" Member="Accounts" ThisKey="StaffRole_ID" OtherKey="StaffRole_ID" Type="Account" />
      <Association Name="StaffRole_Staff" Member="Staffs" ThisKey="StaffRole_ID" OtherKey="StaffRole_ID" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.Vaccine" Member="Vaccines">
    <Type Name="Vaccine">
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Vaccine_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Vaccine_Pet" Member="Pets" ThisKey="Vaccine_ID" OtherKey="Vaccine_ID" Type="Pet" />
    </Type>
  </Table>
  <Table Name="dbo.ActiveStaff_View" Member="ActiveStaff_Views">
    <Type Name="ActiveStaff_View">
      <Column Name="Staff_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffRole_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.AdultPets_View" Member="AdultPets_Views">
    <Type Name="AdultPets_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.AvailablePets_View" Member="AvailablePets_Views">
    <Type Name="AvailablePets_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Cat_View" Member="Cat_Views">
    <Type Name="Cat_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Dog_View" Member="Dog_Views">
    <Type Name="Dog_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.InactiveStaff_View" Member="InactiveStaff_Views">
    <Type Name="InactiveStaff_View">
      <Column Name="Staff_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_FirstName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_LastName" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="StaffRole_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Staff_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.InStockItems_View" Member="InStockItems_Views">
    <Type Name="InStockItems_View">
      <Column Name="Item_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Availability" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.OutOfStockItems_View" Member="OutOfStockItems_Views">
    <Type Name="OutOfStockItems_View">
      <Column Name="Item_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_Description" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Item_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Stock" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Item_Availability" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.SeniorPets_View" Member="SeniorPets_Views">
    <Type Name="SeniorPets_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.SoldPets_View" Member="SoldPets_Views">
    <Type Name="SoldPets_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.UnvaccinatedPets_View" Member="UnvaccinatedPets_Views">
    <Type Name="UnvaccinatedPets_View">
      <Column Name="Pet_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.VaccinatedPets_View" Member="VaccinatedPets_Views">
    <Type Name="VaccinatedPets_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.YoungPets_View" Member="YoungPets_Views">
    <Type Name="YoungPets_View">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.Proc_Add_Item" Method="Proc_Add_Item">
    <Parameter Name="Item_ID" Parameter="item_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item_Description" Parameter="item_Description" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item_Price" Parameter="item_Price" Type="System.Int32" DbType="Int" />
    <Parameter Name="Item_Stock" Parameter="item_Stock" Type="System.Int32" DbType="Int" />
    <Parameter Name="Item_Availability" Parameter="item_Availability" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item_Photo" Parameter="item_Photo" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Proc_Add_Origin" Method="Proc_Add_Origin">
    <Parameter Name="Origin_ID" Parameter="origin_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Origin_FirstName" Parameter="origin_FirstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Origin_LastName" Parameter="origin_LastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Origin_ContactNumber" Parameter="origin_ContactNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Origin_Email" Parameter="origin_Email" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Proc_Add_Owner" Method="Proc_Add_Owner">
    <Parameter Name="Owners_ID" Parameter="owners_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Owners_FirstName" Parameter="owners_FirstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Owners_LastName" Parameter="owners_LastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Owners_ContactNumber" Parameter="owners_ContactNumber" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Owners_Email" Parameter="owners_Email" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Proc_Add_Pet" Method="Proc_Add_Pet">
    <Parameter Name="Pet_ID" Parameter="pet_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Name" Parameter="pet_Name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Type" Parameter="pet_Type" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Sex" Parameter="pet_Sex" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Pedigree" Parameter="pet_Pedigree" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Color" Parameter="pet_Color" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Birthday" Parameter="pet_Birthday" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Pet_Growth" Parameter="pet_Growth" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Vaccine_ID" Parameter="vaccine_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Info" Parameter="pet_Info" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Price" Parameter="pet_Price" Type="System.Int32" DbType="Int" />
    <Parameter Name="Pet_Status" Parameter="pet_Status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Origin_ID" Parameter="origin_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Owners_ID" Parameter="owners_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_Photo" Parameter="pet_Photo" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Proc_Add_Purchase" Method="Proc_Add_Purchase">
    <Parameter Name="Purchase_ID" Parameter="purchase_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Pet_ID" Parameter="pet_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item_ID" Parameter="item_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Item_Quantity" Parameter="item_Quantity" Type="System.Int32" DbType="Int" />
    <Parameter Name="Purchase_Total" Parameter="purchase_Total" Type="System.Int32" DbType="Int" />
    <Parameter Name="Purchase_Date" Parameter="purchase_Date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="Owners_ID" Parameter="owners_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Customer_Number" Parameter="customer_Number" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Staff_ID" Parameter="staff_ID" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Proc_Add_Staff" Method="Proc_Add_Staff">
    <Parameter Name="Staff_ID" Parameter="staff_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Staff_FirstName" Parameter="staff_FirstName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Staff_LastName" Parameter="staff_LastName" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="StaffRole_ID" Parameter="staffRole_ID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Staff_Status" Parameter="staff_Status" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Staff_Photo" Parameter="staff_Photo" Type="System.Data.Linq.Binary" DbType="Image" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.Procedure_Filters_1" Method="Procedure_Filters_1">
    <Parameter Name="F1" Parameter="f1" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Procedure_Filters_1Result">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Procedure_Filters_2" Method="Procedure_Filters_2">
    <Parameter Name="F1" Parameter="f1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F2" Parameter="f2" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Procedure_Filters_2Result">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Procedure_Filters_3" Method="Procedure_Filters_3">
    <Parameter Name="F1" Parameter="f1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F2" Parameter="f2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F3" Parameter="f3" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Procedure_Filters_3Result">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Procedure_Filters_4" Method="Procedure_Filters_4">
    <Parameter Name="F1" Parameter="f1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F2" Parameter="f2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F3" Parameter="f3" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F4" Parameter="f4" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Procedure_Filters_4Result">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.Procedure_Filters_5" Method="Procedure_Filters_5">
    <Parameter Name="F1" Parameter="f1" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F2" Parameter="f2" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F3" Parameter="f3" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F4" Parameter="f4" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="F5" Parameter="f5" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="Procedure_Filters_5Result">
      <Column Name="PET_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Type" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Sex" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Pedigree" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Color" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Birthday" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Growth" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Vaccine_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Info" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Pet_Price" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Pet_Status" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Origin_ID" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Owners_ID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>