//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetShop.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-ROMERO\\SQLEXPRESS;Initial Catalog=\"Pet Shop Database\";Integrat" +
            "ed Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;")]
        public string Pet_Shop_DatabaseConnectionString1 {
            get {
                return ((string)(this["Pet_Shop_DatabaseConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=LAPTOP-ROMERO\\SQLEXPRESS;Initial Catalog=\"Pet Shop Database\";Integrat" +
            "ed Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False")]
        public string Pet_Shop_DatabaseConnectionString2 {
            get {
                return ((string)(this["Pet_Shop_DatabaseConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-ETCNUFV\\SQLEXPRESS;Initial Catalog=\"Pet Shop Database\";Integr" +
            "ated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;" +
            "")]
        public string Pet_Shop_DatabaseConnectionString {
            get {
                return ((string)(this["Pet_Shop_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-ETCNUFV\\SQLEXPRESS;Initial Catalog=\"Pet Shop Database\";Integr" +
            "ated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" +
            "")]
        public string Pet___Item_Shop_DatabaseConnectionString {
            get {
                return ((string)(this["Pet___Item_Shop_DatabaseConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DESKTOP-ETCNUFV\\SQLEXPRESS;Initial Catalog=\"Pet Shop Database\";Integr" +
            "ated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" +
            "")]
        public string Pet_Shop_DatabaseConnectionString3 {
            get {
                return ((string)(this["Pet_Shop_DatabaseConnectionString3"]));
            }
        }
    }
}
